module.exports = [
  {
    roll: "טיפול במפגעים",
    name: "מוקד עירוני",
    tag: "city",
    phoneNumber: "",
    email: "",
    officePhone: "035011111",
  },
  {
    roll: "ממונה בטיחות",
    name: "נורית ביבי",
    tag: "city",
    phoneNumber: "0508375035",
    email: "nuritbi@Holon.muni.il",
    officePhone: "035086100",
  },
  {
    roll: "מנהלת המחלקה לטיפול בפרט",
    name: "רותי יצקן",
    tag: "city",
    phoneNumber: "0523287544",
    email: "rutyy@Holon.muni.il",
    officePhone: "035027298",
  },
  {
    roll: " מפקחת החינוך המיוחד",
    name: "אולגה פישר",
    tag: "matya",
    phoneNumber: "",
    email: "olgafi@education.gov.il",
    officePhone: "",
  },
  {
    roll: "רכזת הגיל הרך",
    name: "גילה שוורץ",
    tag: "matya",
    phoneNumber: "0507773734",
    email: "gilashw@gmail.com",
    officePhone: "",
  },
  {
    roll: 'מנהלת מתי"א חולון-אזור ',
    name: "עידית רמז",
    tag: "matya",
    phoneNumber: "",
    email: "idit.remez@matya365.org.il",
    officePhone: "036541373",
  },
  {
    roll: "רכזת מקצועות הבריאות",
    name: "איילה גולדמן",
    tag: "matya",
    phoneNumber: "0522595232 ",
    email: "ayalafik@gmail.com",
    officePhone: "035598812",
  },
  {
    roll: 'יועצת גני חנ"מ',
    name: "גל שלמה",
    tag: "matya",
    phoneNumber: "050-6509050",
    email: "galsh75@gmail.com",
    officePhone: "",
  },
  {
    roll: "מנהלת מחלקת גני ילדים",
    name: "גילה יצחקי",
    tag: "city",
    phoneNumber: "0522595232 ",
    email: "gilai@holon.muni.il",
    officePhone: "035027393",
  },
  {
    roll: "תחזוקה וגינון",
    name: "חברת זוהר",
    tag: "city",
    phoneNumber: " ",
    email: "",
    officePhone: "039213333",
  },
  {
    roll: 'מנכ"ל חברת זוהר',
    name: "יורם אורן",
    tag: "city",
    phoneNumber: "0544598202",
    email: "",
    officePhone: "",
  },
  {
    roll: "הנהלה",
    name: "חברת מוסדות",
    tag: "city",
    phoneNumber: "",
    email: "mosdoth@matnasim.org.il",
    officePhone: "035012628",
  },
  {
    roll: "אחראית סייעות טכניות",
    name: "אורנה בן אבו",
    tag: "city",
    phoneNumber: "0528457208",
    email: "orna@holon.matnasim.co.il",
    officePhone: "035013815",
  },
  {
    roll: "אחראית סייעות פדגוגיות",
    name: "ענת סידי",
    tag: "city",
    phoneNumber: "0547376355 ",
    email: "anat1@holon.matnasim.co.il",
    officePhone: "036506470",
  },
  {
    roll: "אחראית מחשבים",
    name: "אהובה מימון",
    tag: "city",
    phoneNumber: "",
    email: "ahuvam@Holon.muni.il",
    officePhone: "035027231",
  },
  {
    roll: "אחראית מלווים בהסעות ",
    name: "נאוה",
    tag: "city",
    phoneNumber: "0525775512",
    email: "navaa@holonet.org.il",
    officePhone: "036223835",
  },
  {
    roll: 'טלר כ"א משרד החינוך',
    name: "מיכל הוכמן",
    tag: "other",
    phoneNumber: "",
    email: "michalho@education.gov.il",
    officePhone: "036896330",
  },
  {
    roll: "פעילויות העשרה",
    name: "סל תרבות",
    tag: "city",
    phoneNumber: "",
    email: "",
    officePhone: "035027382 ",
  },
  {
    roll: "שוברי סל תרבות",
    name: 'מתנ"ס גולדה',
    tag: "city",
    phoneNumber: "",
    email: "",
    officePhone: "035041414 ",
  },
  {
    roll: "מחלקת רכש וציוד",
    name: "מיטל מיד",
    tag: "city",
    phoneNumber: "",
    email: "",
    officePhone: "035027372",
  },
  {
    roll: "מחלקת אינוונטר",
    name: "סימה",
    tag: "city",
    phoneNumber: "036536005",
    email: "",
    officePhone: "036536001",
  },
  {
    roll: "מדריכה",
    name: "הילה חזן",
    tag: "matya",
    phoneNumber: "0543033616",
    email: "hilamir@gmail.com",
    officePhone: "",
  },
  {
    roll: "מדריכה",
    name: "אתי זוהר",
    tag: "matya",
    phoneNumber: "0502303055",
    email: "etizo25@gmail.com",
    officePhone: "",
  },
  {
    roll: "אחראית כספים",
    name: "סהר חיון",
    tag: "city",
    phoneNumber: "",
    email: "saharh@Holon.muni.il",
    officePhone: "035027344",
  },
  {
    roll: "מנהלת גן אדמון",
    name: "מיטל משאלי",
    tag: "kinder",
    phoneNumber: "0545902982",
    email: "88meital@walla.co.il",
    officePhone: "",
  },
  {
    roll: "עמיתה גן דרורים",
    name: "לילך דוידוביץ",
    tag: "kinder",
    phoneNumber: "0523590588",
    email: "lilachdavidovich80@gmail.com ",
    officePhone: "",
  },
  {
    roll: "מנהלת מחלקת היסעים",
    name: "שירלי שרף",
    tag: "city",
    phoneNumber: "0545590045",
    email: "",
    officePhone: "035027399",
  },
];
