export default {
  root: {
    backgroundImage: " linear-gradient(-225deg, #E3FDF5 0%, #FFE6FA 100%)",
    backgroundImage: "linear-gradient(to top, #a8edea 0%, #fed6e3 100%)",
    backgroundAttachment: "fixed",
    backgroundRepeat: "no-repeat",
    height: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  form: {
    width: " 450px",
    minHeight: "500px",
    height: "auto",

    margin: "2% auto",
    boxShadow: "0 9px 50px hsla(20, 67%, 75%, 0.31)",
    padding: "2%",
    backgroundImage: "linear-gradient(-225deg, #E3FDF5 50%, #FFE6FA 50%)",
  },
  container: {
    display: "-webkit-flex",
    display: "flex",
    border: "2px solid gray",
    borderRadius: "5px",
    // "-webkit-justify-content": "space-around",
    // "-webkit-flex-wrap": "wrap",
    justifyContent: "space-around",
    flexWrap: "wrap",
    margin: "0 auto",
    width: "60%",
  },
  headForm: {
    fontSize: "100%",

    color: "#3e403f",
    textAlign: "center",
  },
  //   formField: {},
  //   inputItem: {
  //     background: " #fff",
  //     color: " #333",
  //     padding: "14.5px 0px 15px 9px",
  //     borderRadius: "5px 0px 0px 5px",
  //   },
  formInput: {
    fontSize: "16px",
    height: "2rem",
    width: " 90%",
    color: "#5E6472",
    outline: "none",
    border: "none",
    borderRadius: " 5px",
    transition: "0.2s linear",
  },
  signIn: {
    display: "inline-block",
    color: "#252537",
    width: "280px",
    height: "40px",
    padding: "0 20px",
    background: "#fff",
    borderRadius: "5px",
    outline: "none",
    border: "none",
    cursor: " pointer",
    textAlign: "center",
    transition: "all 0.2s linear",
    margin: " 7% auto",
    letterSpacing: " 0.05em",
    width: "48%",
    display: "inline-block",
    marginLeft: " 2%",
  },
};
